# Generated by Django 4.0.5 on 2022-07-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junietunes', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
